ROUTINE l5.Execute

    set client = ##class(l5.Client).%New()
    set client.BirthDate = $ZDATE(21400) ; returns 08/04/1899
    write client.GetAge(), !

    write ##class(l5.Client).Populate(10, 0), !
    write ##class(l5.Manager).Populate(10, 0), !
    write ##class(l5.SparePart).Populate(10, 0), !
    write ##class(l5.Order).Populate(10, 0), !

    set ^UnitTestRoot = "/tests"
    do ##class(%UnitTest.Manager).RunTest("Test:l5.Test", "/noload/norecursive/nodelete")
